### ISSUE TITLE
Question: how does matchFields work exactly?

### ISSUE THREAD

**Issue by elie222** [meanie/mongoose-upsert-many#2]
```js
//Large amount of items
const items = [
  ...
];

//Fields to match on for upsert condition
const matchFields = ['foo', 'bar.nested'];

//Perform bulk operation
const result = await MyModel.upsertMany(items, matchFields);
```

So if there's a doc in the db that has `foo: 1` and `bar.nested: 2`, and an item with this data also exists in the list, then this doc will update the previous one, otherwise it will update it?

Thanks

**Comment by adamreisnz** [comment]
It allows you to specify what fields to match on for the bulk operation. So let's say you have items with properties like so:

```
{
  _id: 'someId',
  foo: 2,
  bar: {
    nested: 3,
  },
  other: 'text',
}
```

Then if you specify `['foo', 'bar.nested']` as the match fields, it will try to find an existing item in your collection which matches those properties, so for the example item it would result in a `bulk.find({foo: 2, 'bar.nested': 3})`.

The default is to use only `_id`, so that's useful if you have pre-generated ID's for your items. Let me know if that clarifies.

**Comment by elie222** [comment]
So if I have:

```js
const items = [
{
  _id: 'someId1',
  foo: 2,
  bar: {
    nested: 3,
  },
  other: 'text',
},
{
  _id: 'someId2',
  foo: 1,
  bar: {
    nested: 2,
  },
  other: 'new text',
},
]
```

And the current db has:

```js
{
  _id: 'someId3',
  foo: 4,
  bar: {
    nested: 5,
  },
  other: 'text',
},
{
  _id: 'someId4',
  foo: 1,
  bar: {
    nested: 2,
  },
  other: 'text',
},
```

Then the update will cause the doc with `someId4` to be updated and the doc with `someId1` to be inserted?

**Comment by elie222** [comment]
Thanks tested it out just now. As explained above for anyone else that's wondering.

**Comment by adamreisnz** [comment]
Yes that's correct, provided you supply those match fields. Otherwise it
will try to match on _id
